export {
  alignedFrameAspect,
  bboxIntersects,
  clamp,
  containedImageRect,
  cropAspectRatio,
  filterOverlayBBoxes,
  fittedImageRect,
  geminiBBoxToDisplayRect,
  clampMarkToPhoto,
  clusterOverlayColumns,
  estimatePrintedRowHeight,
  gradeMarkFromMappedBox,
  gradeMarkLayout,
  isBlankStudentAnswer,
  isDisplayRectVisible,
  isGeminiBBox,
  isInsideLetterbox,
  isMarkInsidePhoto,
  isPlausibleGeminiBBox,
  layoutAlignedGradeMarks,
  letterboxImageRect,
  mapGeminiBBoxToLetterbox,
  mapGeminiBBoxToView,
  sizeAfterExifOrientation,
  unionGeminiBBox,
  problemAreaFitTransform,
  FIT_PADDING_RATIO,
  FIT_VIEW_INSET_RATIO,
  MARK_RADIUS,
  MARK_RADIUS_MAX,
  MARK_RADIUS_MIN,
  MARK_ROW_SIZE_RATIO,
  MARK_SIZE_MAX,
  MARK_SIZE_MIN,
  MARK_STROKE_WIDTH,
  PHOTO_Y_MAX_RATIO,
} from "./lib/overlay-layout.mjs";

export type LayoutRect = { x: number; y: number; width: number; height: number };
